baseURL = "https://zando.io/"
title = "Alex Bowers' Blog"

languageCode = "en-gb"

theme = "hugo-cactus-theme"
publishDir = "docs"

googleAnalytics = "UA-78319221-1"

[params]
  name = "Alex Bowers' Blog"
  twitter = "bowersbros"
  enableRSS = false

  enableDisqus = false
  enableGithubIssuesTips = true
  enableGoogleAnalytics = false
  enableBaiduAnalytics = false

  about = ""

[social]
  twitter = "https://twitter.com/bowersbros"
  github = "https://github.com/alexbowers"
